script:
- mkdir _build
- xelatex -output-directory _build document.tex
deploy:
  provider: releases
  api_key:
    secure: R7Uw5amCwSyKSYFCJLPq4GMA/vcZuC7XrhJM5pOhQ/WkMj8OC+WbsaUBHkr7MkAnjYJVMZSOR8tveI7rFKvrWbspEO3R5hPhm2xkEhfnMQafJcjM15nirk+n9Yw5yodu3PH0Y924ZZiQkLpiNAIzaIz2VVlpmr/Y6cBDdLwgVgI=
  file: 
- _build/document.pdf
  on:
    repo: dev23cc/PedagogicsProjectPresentation
