install:
- git archive --format zip --output source.zip master
- sudo apt-get install p7zip-full texlive-fonts-recommended fonts-gfs-didot-classic ttf-gfs-didot-classic ttf-gfs-complutum ttf-gfs-solomos ttf-gfs-baskerville ttf-gfs-neohellenic ttf-gfs-didot
- wget http://tug.ctan.org/systems/texlive/Images/texlive.iso
- wget https://gist.githubusercontent.com/dev23cc/ee158185167cc2499ec2/raw/6d62a94977c57ff8a1d4da09e2737b3b620313aa/texlive.profile
- 7z x texlive.iso
- chmod +x install-tl
- sudo ./install-tl --profile=texlive.profile
script:
- mkdir _build
- source /etc/environment
- /usr/local/texlive/2014/bin/x86_64-linux/xelatex -output-directory=_build document.tex
deploy:
  provider: releases
  api_key:
    secure: R7Uw5amCwSyKSYFCJLPq4GMA/vcZuC7XrhJM5pOhQ/WkMj8OC+WbsaUBHkr7MkAnjYJVMZSOR8tveI7rFKvrWbspEO3R5hPhm2xkEhfnMQafJcjM15nirk+n9Yw5yodu3PH0Y924ZZiQkLpiNAIzaIz2VVlpmr/Y6cBDdLwgVgI=
  file: _build/document.pdf
  on:
    tags: true
    repo: dev23cc/PedagogicsProjectPresentation
