install:
- latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
- git archive --format zip --output source.zip  $latestTag
- FIRSTTAG=$(git describe --tags --always --dirty='-*' 2>/dev/null)
- RELTAG=$(git describe --tags --long --always --dirty='-*' --match '[0-9]*.*' 2>/dev/null)
#- git --no-pager log -1 --date=short --decorate=short \
#    --pretty=format:"\usepackage[%
#        shash={%h},
#        lhash={%H},
#        authname={%an},
#        authemail={%ae},
#        authsdate={%ad},
#        authidate={%ai},
#        authudate={%at},
#        commname={%an},
#        commemail={%ae},
#        commsdate={%ad},
#        commidate={%ai},
#        commudate={%at},
#        refnames={%d},
#        firsttagdescribe={$FIRSTTAG},
#        reltag={$RELTAG}
#    ]{gitexinfo}" HEAD > .git/gitHeadInfo.gin
- sudo apt-get install p7zip-full fonts-gfs-didot-classic ttf-gfs-didot-classic ttf-gfs-complutum ttf-gfs-solomos ttf-gfs-baskerville ttf-gfs-neohellenic ttf-gfs-didot
- wget http://tug.ctan.org/systems/texlive/Images/texlive.iso
- wget https://gist.githubusercontent.com/dev23cc/ee158185167cc2499ec2/raw/6d62a94977c57ff8a1d4da09e2737b3b620313aa/texlive.profile
- 7z x texlive.iso
- chmod +x install-tl
- sudo ./install-tl --profile=texlive.profile
script:
- mkdir _build
- /usr/local/texlive/2014/bin/x86_64-linux/xelatex -output-directory=_build document.tex
- /usr/local/texlive/2014/bin/x86_64-linux/xelatex -output-directory=_build document.tex
deploy:
  provider: releases
  api_key:
    secure: meVzVbBYNSV1C/Z0AAHmViFjnV9QyXbvEFZ5EMCMKZqxX3gX4ME1vcbcDaM3OVf3DbXw2WG6OtE7D/J3sfz46CmmF/3SDHRgG6CJxcZtt74qF3JHuZ98Hq+xuWA01F+E1lXEGYhLs6Vd1xWfWsaUrqtFv/hmLmeMWLOZdq1apWy5dGZqyhlTTLPd6SYB7Ir+YT4E/0vqGGaLWX3zvt7rPvCuIGT/RiJoLi+4YdeKKlk+EKr6O3mFQtJ+WyCm5dBXft71q1AHZd8OK8v9ZWBW+q2m7RWUl0+o7Y1cktwJJAftD0MQv3EkfxyazJ/57MJZpAugRn7d0wWUZbfehBaMmJCiYF3NTPddqPOPO9Kd4flvgvtx5f6uJkqqAGfMpS3e0CwYkNWbK9i7t60PXW86gsCqncqDcuSzCBoowkORXs4tlR45uU4F/AsQRc46UrCmio0lE6ea+16sDMktDt+t3OPC5HhdVbt1N65vBz5j5konzXw1L5b2uyPvfQu2fwtcgoE2pMGAJQmGTghz5Tyko4sqUWNTI54H6bql/C33gNC8IY/frhj9jFCFrF6qGCX9C1qPPcsDDSi2n85tfDieCdacNFLqn/7uErKPzcUpVL31kXBjebxcpPv4euBcn/awwRtnZ1JDiyaVZAaebeSDnAlJUDEgHDXIq2Yu8saWf9Q=
  file: _build/document.pdf
  on:
    tags: true
    repo: latex-projects/AnalogElectronicsProblems

